### ISSUE TITLE
Getting a invalid Json error

### ISSUE THREAD

**Issue by jouderianjr** [zwilias/elm-coverage#27]
Hello folks, I'm getting an error trying to run the `elm-coverage`
`Received invalid JSON from test interface search: SyntaxError: Unexpected token e in JSON at position 0` I notice that this come from `elm-test --compiler /Users/jouderianjr/.npm-global/lib/node_modules/elm-coverage/bin/fake-elm tests/`. 

The thing is when I run `elm-test` it works and all the tests pass. does someone know what could be wrong? 

P.S it is elm 0.19.1

**Comment by ceddlyburge** [comment]
I also see this. It works with Elm 0.19.0

**Comment by YauhenPylAurea** [comment]
Hello, I had the same issue. Is there any solution? Thanks. (elm 0.19.1, elm-test 0.19.1, windows 10)

**Comment by marc136** [comment]
It seems like the issue is related to elmi-to-json (which is used in the outdated elm-test@0.19.1-revision2 that is currently hardcoded in elm-coverage). At least the error message looks like the one reported in elm-test https://github.com/rtfeldman/node-test-runner/issues/258#issuecomment-722635264 and there it was solved by removing elmi-to-json.
So I think that PR #31 also fixes this bug.

In my tests, elm-coverage reports were generated on linux and windows when used with the current elm-test@0.19.1-revision6.

**Comment by zwilias** [comment]
Should be fine with latest (>0.4.0) version 🎉
